#!/bin/bash

ensure_not_exists() {
    if [[ ( -e "$1" ) || ( -L "$1" ) ]]; then
        rm -rf "$1"
    fi
}

ensure_parent_dir_exists() {
    parent_dir=$(dirname $1)
    if [[ ! -e "${parent_dir}" ]]; then
        mkdir -p "${parent_dir}"
    fi
}

path_join() {
    echo "${1%%/}$2"
}

force_link() {
    ensure_not_exists "$(path_join $2 $3)"
    ensure_parent_dir_exists "$(path_join $2 $3)"
    ln -s "$(path_join $1 $3)" "$(path_join $2 $3)"
}

backup_link() {
    ensure_not_exists "$(path_join $1 $3)"
    ensure_parent_dir_exists "$(path_join $1 $3)"
    mv "$(path_join $2 $3)" "$(path_join $1 $3)"
    force_link "$1" "$2" "$3"
}

auto_link() {
    if [[ -e "$(path_join $1 $3)" ]]; then
        force_link "$1" "$2" "$3"
    elif [[ -e "$(path_join $2 $3)" ]]; then
        backup_link "$1" "$2" "$3"
    else
        ensure_parent_dir_exists "$(path_join $1 $3)"
        force_link "$1" "$2" "$3"
    fi
}

setup_linker() {
    if [[ "${IVY_PATH}" = "" ]]; then
        return
    fi

    for i in $(echo "${IVY_PATH}" | tr ";" "\n"); do
        if [[ "$i" != "" ]]; then
            auto_link "${IVY_SOURCE}" "${IVY_TARGET}" "$i"
        fi
    done
}

setup_linker
